FROM node:lts-alpine

WORKDIR /app

RUN addgroup -g 1001 -S iverify && adduser -u 1001 -S iverify  -G iverify 
RUN chown -R iverify:iverify /app

USER iverify


COPY ./dist/apps/triage .

ENV PORT=3335
EXPOSE 3335
RUN npm install --production
RUN npm install reflect-metadata tslib rxjs @nestjs/platform-express

CMD node ./main.js