version: '3.3'
services:
    triage:
        image: triage
        build:
            context: .
            dockerfile: apps/triage/Dockerfile
        ports:
            - '3335:3335'
        env_file: 
            - .env
    publisher:
        build:
            context: .
            dockerfile: apps/publisher/Dockerfile
        image: publisher
        ports:
            - '3334:3334'
        env_file: 
            - .env
