// export enum TasksLabels{
//     claim = 'Claim',
//     rating_justification = 'Rating Justification',
//     evidences_and_references = 'Evidence and References',
//     card_title = 'Card Title',
//     toxic = 'Toxic Score',
//     threat_level = 'Threat level',
//     violation_type = 'Type of Violation',
//     disinfo_type = 'Mis/Disinformation Type',
//     hate_speech_type = 'Hate Speech Type',
//     toxic_score = 'Toxic Score',
//     obscene_score = 'Obscene Score',
//     identity_score = 'Attack on Identity Score',
//     threat_score = 'Threat Score ',
//     sexually_explicit_score = 'Sexually Explicit Score',
// }

export const TasksLabels = {
    en: {
        claim: 'Claim',
        rating_justification: 'Rating Justification',
        evidences_and_references: 'Evidence and References',
        card_title: 'Card Title',
        toxic: 'Toxic Score',
        threat_level: 'Threat level',
        violation_type: 'Type of Violation',
        disinfo_type: 'Mis/Disinformation Type',
        hate_speech_type: 'Hate Speech Type',
        toxic_score: 'Toxic Score',
        obscene_score: 'Obscene Score',
        identity_score: 'Attack on Identity Score',
        threat_score: 'Threat Score ',
        sexually_explicit_score: 'Sexually Explicit Score',
    },
    es: {
        claim: 'Declaración',
        rating_justification: 'Justificación de la evaluación',
        evidences_and_references: 'Evidencia y Referencias',
        card_title: 'Card Title',
        toxic: 'Tipo de discurso de odio',
        threat_level: 'Threat level',
        violation_type: 'Tipo de amenaza',
        disinfo_type: 'Tipo de desinformación',
        hate_speech_type: 'Tipo de discurso de odio',
        toxic_score: 'Tóxico (puntuación)',
        obscene_score: 'Obsceno (puntuación)',
        identity_score: 'Ataque a la identidad (puntuación)',
        threat_score: 'Amenaza (puntuación)',
        sexually_explicit_score: 'Sexualmente explicito (puntuación)',
    }
}