

export const TasksLabels = {
    en: {
        claim: 'Claim',
        rating_justification: 'Rating Justification',
        evidences_and_references: 'Evidence and References',
        card_title: 'Card Title',
        toxic: 'Toxic Score',
        threat_level: 'Threat level',
        violation_type: 'Type of Violation',
        disinfo_type: 'Mis/Disinformation Type',
        hate_speech_type: 'Hate Speech Type',
        toxic_score: 'Toxic Score',
        obscene_score: 'Obscene Score',
        identity_score: 'Attack on Identity Score',
        threat_score: 'Threat Score ',
        sexually_explicit_score: 'Sexually Explicit Score',
        d_toxic_score: 'Detoxify score',
        d_severe_toxic_score: 'Detoxify severe toxicity score',
        d_obscene_score: 'Detoxify obscene score',
        d_identity_score: 'Detoxify identity attack score',
        d_insult_score: 'Detoxify insult score',
        d_threat_score: 'Detoxify threat score',
        d_sexually_explicit_score: 'Detoxify sexual explicit score',
        violation_disinfo: 'Disinformation',
        violation_misinfo: 'Misinformation',
        violation_hate_speech: 'Hate Speech',
        violation_threat: 'Threat / Intimidation',
        violation_violence: 'Incitement Of Violence',
        violation_no_threat: 'No violation noted',
        status_unstarted: 'Unstarted',
        status_in_progress: 'In Progress',
        status_false: 'False',
        status_true: 'True',
        status_misleading: 'Misleading',
        status_out_of_scope: 'Out of scope',
        status_partly_false: 'Partly false',
        status_inconclusive: 'Inconclusive',
        status_pre_checked: 'Pre-checked'

    },
    es: {
        claim: 'Declaración',
        rating_justification: 'Justificación de la evaluación',
        evidences_and_references: 'Evidencia y Referencias',
        card_title: 'Card Title',
        toxic: 'Tipo de discurso de odio',
        threat_level: 'Threat level',
        violation_type: 'Tipo de amenaza',
        disinfo_type: 'Tipo de desinformación',
        hate_speech_type: 'Tipo de discurso de odio',
        toxic_score: 'Tóxico (puntuación)',
        obscene_score: 'Obsceno (puntuación)',
        identity_score: 'Ataque a la identidad (puntuación)',
        threat_score: 'Amenaza (puntuación)',
        sexually_explicit_score: 'Sexualmente explicito (puntuación)',
        d_toxic_score: 'Detoxify score',
        d_severe_toxic_score: 'Detoxify severe toxicity score',
        d_obscene_score: 'Detoxify obscene score',
        d_identity_score: 'Detoxify identity attack score',
        d_insult_score: 'Detoxify insult score',
        d_threat_score: 'Detoxify threat score',
        d_sexually_explicit_score: 'Detoxify sexual explicit score',
        violation_disinfo: 'Desinformación',
        violation_misinfo: 'Desinformación',
        violation_hate_speech: 'Discurso del odio',
        violation_threat: 'Amenaza / Intimidación',
        violation_violence: 'Incitación a la violencia',
        violation_no_threat: 'No se ha observado ninguna amenaza',
        status_unstarted: 'Sin iniciar',
        status_in_progress: 'En curso',
        status_false: 'Falso',
        status_true: 'Verdadero',
        status_misleading: 'fraudolento',
        status_out_of_scope: 'Fuera de perspectiva',
        status_partly_false: 'Sostenible',
        status_inconclusive: 'No confirmado',
        status_pre_checked: 'Pre-comprobado'
    }
}