export const TasksLabels = {
    en: {
        claim: 'Claim',
        rating_justification: 'Rating Justification',
        evidences_and_references: 'Evidence and References',
        card_title: 'Card Title',
        toxic: 'Toxic Score',
        threat_level: 'Threat level',
        violation_type: 'Type of Violation',
        disinfo_type: 'Mis/Disinformation Type',
        hate_speech_type: 'Hate Speech Type',
        toxic_score: 'Toxic Score',
        obscene_score: 'Obscene Score',
        identity_score: 'Attack on Identity Score',
        threat_score: 'Threat Score ',
        sexually_explicit_score: 'Sexually Explicit Score',
        d_toxic_score: 'Detoxify score',
        d_severe_toxic_score: 'Detoxify severe toxicity score',
        d_obscene_score: 'Detoxify obscene score',
        d_identity_score: 'Detoxify identity attack score',
        d_insult_score: 'Detoxify insult score',
        d_threat_score: 'Detoxify threat score',
        d_sexually_explicit_score: 'Detoxify sexual explicit score',
        violation_disinfo: 'Disinformation',
        violation_misinfo: 'Misinformation',
        violation_hate_speech: 'Hate Speech',
        violation_threat: 'Threat / Intimidation',
        violation_violence: 'Incitement Of Violence',
        violation_no_threat: 'No violation noted',
        status_unstarted: 'Unstarted',
        status_in_progress: 'In Progress',
        status_false: 'False',
        status_true: 'True',
        status_misleading: 'Misleading',
        status_out_of_scope: 'Out of scope',
        status_partly_false: 'Partly false',
        status_inconclusive: 'Inconclusive',
        status_pre_checked: 'Pre-checked',
        category_checked:'Category',
        email_address: 'Email Address',
        upload_file: 'Upload Files',
        audio_url:'audio_url',
        message:'message'
    },
    es: {
        claim: 'Declaración',
        rating_justification: 'Justificación de la evaluación',
        evidences_and_references: 'Evidencia y Referencias',
        card_title: 'Card Title',
        toxic: 'Tipo de discurso de odio',
        threat_level: 'Threat level',
        violation_type: 'Tipo de amenaza',
        disinfo_type: 'Tipo de desinformación',
        hate_speech_type: 'Tipo de discurso de odio',
        toxic_score: 'Tóxico (puntuación)',
        obscene_score: 'Obsceno (puntuación)',
        identity_score: 'Ataque a la identidad (puntuación)',
        threat_score: 'Amenaza (puntuación)',
        sexually_explicit_score: 'Sexualmente explicito (puntuación)',
        d_toxic_score: 'Detoxify score',
        d_severe_toxic_score: 'Detoxify severe toxicity score',
        d_obscene_score: 'Detoxify obscene score',
        d_identity_score: 'Detoxify identity attack score',
        d_insult_score: 'Detoxify insult score',
        d_threat_score: 'Detoxify threat score',
        d_sexually_explicit_score: 'Detoxify sexual explicit score',
        violation_disinfo: 'Desinformación',
        violation_misinfo: 'Desinformación',
        violation_hate_speech: 'Discurso del odio',
        violation_threat: 'Amenaza / Intimidación',
        violation_violence: 'Incitación a la violencia',
        violation_no_threat: 'No se ha observado ninguna amenaza',
        status_unstarted: 'Sin iniciar',
        status_in_progress: 'En curso',
        status_false: 'Falso',
        status_true: 'Verdadero',
        status_misleading: 'fraudolento',
        status_out_of_scope: 'Fuera de perspectiva',
        status_partly_false: 'Sostenible',
        status_inconclusive: 'No confirmado',
        status_pre_checked: 'Pre-comprobado',
        category_checked:'Category',
        email_address: 'Email Address',
        upload_file: 'Upload Files',
        audio_url:'audio_url',
        message:'message'
    },
    fr: {
        claim: 'Affirmation',
        rating_justification: 'Verdict et Processus de Vérification',
        evidences_and_references: 'Evidence and Réferences',
        card_title: 'Card Title',
        toxic: 'Toxic Score',
        threat_level: 'Threat level',
        violation_type: 'Type of Violation',
        disinfo_type: 'Mis/Disinformation Type',
        hate_speech_type: 'Hate Speech Type',
        toxic_score: 'Toxic Score',
        obscene_score: 'Obscene Score',
        identity_score: 'Attack on Identity Score',
        threat_score: 'Threat Score ',
        sexually_explicit_score: 'Sexually Explicit Score',
        d_toxic_score: 'Detoxify score',
        d_severe_toxic_score: 'Detoxify severe toxicity score',
        d_obscene_score: 'Detoxify obscene score',
        d_identity_score: 'Detoxify identity attack score',
        d_insult_score: 'Detoxify insult score',
        d_threat_score: 'Detoxify threat score',
        d_sexually_explicit_score: 'Detoxify sexual explicit score',
        violation_disinfo: 'Disinformation',
        violation_misinfo: 'Misinformation',
        violation_hate_speech: 'Hate Speech',
        violation_threat: 'Threat / Intimidation',
        violation_violence: 'Incitement Of Violence',
        violation_no_threat: 'No violation noted',
        status_unstarted: 'EN ATTENTE DE VÉRIFICATION',
        status_in_progress: 'EN COURS DE VÉRIFICATION',
        status_false: 'Faux',
        status_true: 'Vrai',
        status_misleading: 'Erroné',
        status_out_of_scope: 'Out of scope',
        status_partly_false: 'A Moitié Vrai',
        status_inconclusive: 'Non Prouvé',
        status_pre_checked: 'PRÉ-VÉRIFIÉ',
        category_checked:'Catégorie',
        email_address: 'Adresse E-mail',
        upload_file: 'Téléchargements de fichiers',
        audio_url:'url_audio',
        message:'message'
    },
    mkd: {
      claim: 'Тврдење',
      rating_justification: 'Процес на верификација и давање мислење',
      evidences_and_references: 'Докази и референци',
      card_title: 'Наслов на картичката',
      toxic: 'Оценка за токсичност',
      threat_level: 'Ниво на закана',
      violation_type: 'Вид на прекршок: Изберете го соодветниот вид на прекршок.',
      disinfo_type: 'Тип на дезинформација/погрешна информација',
      hate_speech_type: 'Тип на говор на омраза',
      toxic_score: 'Оценка за токсичност',
      obscene_score: 'Оценка за непристојност',
      identity_score: 'Оценка за напад на идентитет',
      threat_score: 'Оценка за закана',
      sexually_explicit_score: 'Оценка за сексуална експлицитност',
      d_toxic_score: 'Оценка по детоксификација',
      d_severe_toxic_score: 'Оценка по детоксификација на голема токсичност',
      d_obscene_score: 'Оценка по детоксификација на непристојност',
      d_identity_score: 'Оценка по детоксификација на напад на идентитет',
      d_insult_score: 'Оценка по детоксификација на навреда',
      d_threat_score: 'Оценка за детоксификација на закана',
      d_sexually_explicit_score: 'Оценка по детоксификација на сексуална експлицитност',
      violation_disinfo: 'Дезинформација',
      violation_misinfo: 'Погрешна информација',
      violation_hate_speech: 'Говор на омраза',
      violation_threat: 'Закана / заплашување',
      violation_violence: 'Поттикнување насилство',
      violation_no_threat: 'Не е утврдено прекршување',
      status_unstarted: 'Не е почнато',
      status_in_progress: 'Во тек',
      status_false: 'НЕТОЧНО',
      status_true: 'ТОЧНО',
      status_misleading: 'Доведува во заблуда',
      status_out_of_scope: 'Надвор од опсег',
      status_partly_false: 'Делумно неточно',
      status_inconclusive: 'Не може да се донесе заклучок',
      status_pre_checked: 'Однапред проверено',
      category_checked:'Category',
      email_address: 'Email Address',
      upload_file: 'Upload Files',
      audio_url:'audio_url',
      message:'message'
  },
}
