export const TasksLabels = {
    en: {
        claim: 'Claim',
        rating_justification: 'Rating Justification',
        evidences_and_references: 'Evidence and References',
        card_title: 'Card Title',
        toxic: 'Toxic Score',
        threat_level: 'Threat level',
        violation_type: 'Type of Violation',
        disinfo_type: 'Mis/Disinformation Type',
        hate_speech_type: 'Hate Speech Type',
        toxic_score: 'Toxic Score',
        obscene_score: 'Obscene Score',
        identity_score: 'Attack on Identity Score',
        threat_score: 'Threat Score ',
        sexually_explicit_score: 'Sexually Explicit Score',
        d_toxic_score: 'Detoxify score',
        d_severe_toxic_score: 'Detoxify severe toxicity score',
        d_obscene_score: 'Detoxify obscene score',
        d_identity_score: 'Detoxify identity attack score',
        d_insult_score: 'Detoxify insult score',
        d_threat_score: 'Detoxify threat score',
        d_sexually_explicit_score: 'Detoxify sexual explicit score',
        violation_disinfo: 'Disinformation',
        violation_misinfo: 'Misinformation',
        violation_hate_speech: 'Hate Speech',
        violation_threat: 'Threat / Intimidation',
        violation_violence: 'Incitement Of Violence',
        violation_no_threat: 'No violation noted',
        status_unstarted: 'Unstarted',
        status_in_progress: 'In Progress',
        status_false: 'False',
        status_true: 'True',
        status_misleading: 'Misleading',
        status_out_of_scope: 'Out of scope',
        status_partly_false: 'Partly false',
        status_inconclusive: 'Inconclusive',
        status_pre_checked: 'Pre-checked',
        category_checked:'Category',
        email_address: 'Email Address',
        upload_file: 'Upload Files',
        audio_url:'audio_url',
        message:'message',
        original_reported_date: 'original_reported_date',
        meedan_category:'Category'
    },
    es: {
        claim: 'Contenido Verificado',
        rating_justification: 'Veracidad del Contenido',
        evidences_and_references: 'Evidencia y Referencias',
        card_title: 'Título del Contenido',
        toxic: 'Evaluación de Toxicidad',
        threat_level: 'Nivel de Amenaza',
        violation_type: 'Tipo de Contenido',
        disinfo_type: 'Tipo de Desinformación',
        hate_speech_type: 'Tipo de Discurso de Odio',
        toxic_score: 'Evaluación de Toxicidad',
        obscene_score: 'Evaluación de Obscenidad',
        identity_score: 'Evaluación de ataque a la Identidad',
        threat_score: 'Evaluación de Amenaza',
        sexually_explicit_score: 'Evaluación de Contenido Sexual Explicito',
        d_toxic_score: 'Evaluación Detoxify',
        d_severe_toxic_score: 'Evaluación de Toxicidad Severa de Detoxify',
        d_obscene_score: 'Evaluación de Obscenidad de Detoxify',
        d_identity_score: 'Evaluación  de ataque a la Identidad de Detoxify',
        d_insult_score: 'Evaluación  de Insulto de Detoxify',
        d_threat_score: 'Evaluación  de Amenaza de Detoxify',
        d_sexually_explicit_score: 'Evaluación  de Contenido Sexual Explicito de Detoxify',
        violation_disinfo: 'Desinformación',
        violation_misinfo: 'Desinformación',
        violation_hate_speech: 'Discurso de Odio',
        violation_threat: 'Amenaza/ Intimidación',
        violation_violence: 'Incitación a la Violencia',
        violation_no_threat: 'No se observó ninguna Violación',
        status_unstarted: 'Verificación Pendiente',
        status_in_progress: 'En Progreso',
        status_false: 'Falso',
        status_true: 'Verdadero',
        status_misleading: 'Engañoso',
        status_out_of_scope: 'Fuera de perspectiva',
        status_partly_false: 'Sostenible',
        status_inconclusive: 'No comprobado',
        status_pre_checked: 'Pre-comprobado',
        category_checked:'Categoría',
        email_address: 'Direccion de Correo Electronico',
        upload_file: 'Subir Archivos',
        audio_url:'URL de Audio',
        message:'Mensaje',
        original_reported_date: 'Fecha Original de Reporte',
        meedan_category:'Categoría'
    },
    fr: {
        claim: 'Affirmation',
        rating_justification: 'Verdict et Processus de Vérification',
        evidences_and_references: 'Evidence and Réferences',
        card_title: 'Card Title',
        toxic: 'Toxic Score',
        threat_level: 'Threat level',
        violation_type: 'Type of Violation',
        disinfo_type: 'Mis/Disinformation Type',
        hate_speech_type: 'Hate Speech Type',
        toxic_score: 'Toxic Score',
        obscene_score: 'Obscene Score',
        identity_score: 'Attack on Identity Score',
        threat_score: 'Threat Score ',
        sexually_explicit_score: 'Sexually Explicit Score',
        d_toxic_score: 'Detoxify score',
        d_severe_toxic_score: 'Detoxify severe toxicity score',
        d_obscene_score: 'Detoxify obscene score',
        d_identity_score: 'Detoxify identity attack score',
        d_insult_score: 'Detoxify insult score',
        d_threat_score: 'Detoxify threat score',
        d_sexually_explicit_score: 'Detoxify sexual explicit score',
        violation_disinfo: 'Disinformation',
        violation_misinfo: 'Misinformation',
        violation_hate_speech: 'Hate Speech',
        violation_threat: 'Threat / Intimidation',
        violation_violence: 'Incitement Of Violence',
        violation_no_threat: 'No violation noted',
        status_unstarted: 'EN ATTENTE DE VÉRIFICATION',
        status_in_progress: 'EN COURS DE VÉRIFICATION',
        status_false: 'Faux',
        status_true: 'Vrai',
        status_misleading: 'Erroné',
        status_out_of_scope: 'Out of scope',
        status_partly_false: 'A Moitié Vrai',
        status_inconclusive: 'Non Prouvé',
        status_pre_checked: 'PRÉ-VÉRIFIÉ',
        category_checked:'Catégorie',
        email_address: 'Adresse E-mail',
        upload_file: 'Téléchargements de fichiers',
        audio_url:'url_audio',
        message:'message',
        original_reported_date: 'date_de_rapport_originale',
        meedan_category:'Catégorie'
    },
    mkd: {
      claim: 'Тврдење',
      rating_justification: 'Процес на верификација и давање мислење',
      evidences_and_references: 'Докази и референци',
      card_title: 'Наслов на картичката',
      toxic: 'Оценка за токсичност',
      threat_level: 'Ниво на закана',
      violation_type: 'Вид на прекршок: Изберете го соодветниот вид на прекршок.',
      disinfo_type: 'Тип на дезинформација/погрешна информација',
      hate_speech_type: 'Тип на говор на омраза',
      toxic_score: 'Оценка за токсичност',
      obscene_score: 'Оценка за непристојност',
      identity_score: 'Оценка за напад на идентитет',
      threat_score: 'Оценка за закана',
      sexually_explicit_score: 'Оценка за сексуална експлицитност',
      d_toxic_score: 'Оценка по детоксификација',
      d_severe_toxic_score: 'Оценка по детоксификација на голема токсичност',
      d_obscene_score: 'Оценка по детоксификација на непристојност',
      d_identity_score: 'Оценка по детоксификација на напад на идентитет',
      d_insult_score: 'Оценка по детоксификација на навреда',
      d_threat_score: 'Оценка за детоксификација на закана',
      d_sexually_explicit_score: 'Оценка по детоксификација на сексуална експлицитност',
      violation_disinfo: 'Дезинформација',
      violation_misinfo: 'Погрешна информација',
      violation_hate_speech: 'Говор на омраза',
      violation_threat: 'Закана / заплашување',
      violation_violence: 'Поттикнување насилство',
      violation_no_threat: 'Не е утврдено прекршување',
      status_unstarted: 'Не е почнато',
      status_in_progress: 'Во тек',
      status_false: 'НЕТОЧНО',
      status_true: 'ТОЧНО',
      status_misleading: 'Доведува во заблуда',
      status_out_of_scope: 'Надвор од опсег',
      status_partly_false: 'Делумно неточно',
      status_inconclusive: 'Не може да се донесе заклучок',
      status_pre_checked: 'Однапред проверено',
      category_checked:'Category',
      email_address: 'Email Address',
      upload_file: 'Upload Files',
      audio_url:'audio_url',
      message:'message',
      original_reported_date: 'original_reported_date',
      meedan_category:'category'

    },
    "en-mw": {
      rating_justification: 'Verdict and Verification Process',
      evidences_and_references: 'Evidence and References',
      violation_type: 'Type of Violation',
      meedan_category:'Category',
      email_address: 'Email Address',
      upload_file: 'Upload Files',
    }
}


export enum MeedanLabels {
  CLAIM = "claim",
  RATING_JUSTIFICATION = "rating_justification",
  EVIDENCES_AND_REFERENCES = "evidences_and_references",
  CARD_TITLE = "card_title",
  TOXIC = "toxic",
  THREAT_LEVEL = "threat_level",
  VIOLATION_TYPE = "violation_type",
  DISINFO_TYPE = "disinfo_type",
  HATE_SPEECH_TYPE = "hate_speech_type",
  TOXIC_SCORE = "toxic_score",
  OBSCENE_SCORE = "obscene_score",
  IDENTITY_SCORE = "identity_score",
  THREAT_SCORE = "threat_score",
  SEXUALLY_EXPLICIT_SCORE = "sexually_explicit_score",
  D_TOXIC_SCORE = "d_toxic_score",
  D_SEVERE_TOXIC_SCORE = "d_severe_toxic_score",
  D_OBSCENE_SCORE = "d_obscene_score",
  D_IDENTITY_SCORE = "d_identity_score",
  D_INSULT_SCORE = "d_insult_score",
  D_THREAT_SCORE = "d_threat_score",
  D_SEXUALLY_EXPLICIT_SCORE = "d_sexually_explicit_score",
  VIOLATION_DISINFO = "violation_disinfo",
  VIOLATION_MISINFO = "violation_misinfo",
  VIOLATION_HATE_SPEECH = "violation_hate_speech",
  VIOLATION_THREAT = "violation_threat",
  VIOLATION_VIOLENCE = "violation_violence",
  VIOLATION_NO_THREAT = "violation_no_threat",
  STATUS_UNSTARTED = "status_unstarted",
  STATUS_IN_PROGRESS = "status_in_progress",
  STATUS_FALSE = "status_false",
  STATUS_TRUE = "status_true",
  STATUS_MISLEADING = "status_misleading",
  STATUS_OUT_OF_SCOPE = "status_out_of_scope",
  STATUS_PARTLY_FALSE = "status_partly_false",
  STATUS_INCONCLUSIVE = "status_inconclusive",
  STATUS_PRE_CHECKED = "status_pre_checked",
  CATEGORY_CHECKED = "category_checked",
  EMAIL_ADDRESS = "email_address",
  UPLOAD_FILE = "upload_file",
  AUDIO_URL = "audio_url",
  MESSAGE = "message",
  ORIGINAL_REPORTED_DATE = "original_reported_date",
  MEEDAN_CATEGORY = "meedan_category",
}
