export enum Permission {
  // ManageUsers = 'Manage Users',
  // ManagePosts = 'Manage Posts',
  ManageSettings = 'Manage Settings',
  BulkDataImportAndExport = 'Bulk Data Import and Export',
  // EditTheirOwnPosts = 'Edit their own posts',
  ManageSetupInfo = 'Access/Edit User Server Setup Information',
  AssignSuperUser = 'Assign Super User Roles',
  CreateUser = 'Create Users',
  AssignRoles = 'Assign User Roles',
  DeleteRoles = 'Delete Users',
  ViewNewDeletedAccounts = 'View Created And Deleted Accounts',
  ViewUserActivity = 'View User Activity',
  EditTheirOwnPosts = 'Edit Incident',
  CreatePost = 'Register Incident',
  ViewPosts = 'View Incidents',
  FilterPosts = 'Filters Incident By Category',
  DeletePosts = 'Delete Incident',
  EditPosts = 'Edit Incident',
  LinkUnlinkPosts = 'Link/Unlink Incident',
  ManageCollectionsAndSavedSearches = 'Manage Collections, Saved Searches and Messages',
  ManagePriority = 'Escalate Incident',
  // Client-defined permissions.
  SubmitPosts = 'Submit Posts',

  AccessEVIEWDashboard = 'Access eview dashboard',
  CreateReport = 'Create report',
  AccessIncidentRiskReports = 'Access incident risk reports',
  ViewIncidentRiskReporterIdentity = 'View incident risk reporter identity',
  ModifyReportInformation = 'Modify report information',
  ModifyPersonalIncidentRiskReports = 'Modify personal incident risk reports',
  AccessAnalysisAndFiltersSection = 'Access analysis and filters section',
  AccessAndModifyParametersSettings = 'Access and modify parameters settings',
  ExportIncidentList = 'Export incident list',
  RequestIncidentRiskReports = 'Request modifications of risk/incident logged by others'
}
