FROM node:14.17.1 as builder

ARG ENVIRONMENT
RUN npm install npm@latest -g

RUN apt-get update && \
  apt-get install -y \
  libgtk2.0-0 \
  libnotify-dev \
  libgconf-2-4 \
  libnss3 \
  libxss1 \
  libasound2 \
  xvfb

WORKDIR /workspace
COPY . .
RUN ls -la 

RUN npm install
ENV PATH /workspace/node_modules/.bin:$PATH
RUN nx build publisher 


FROM node:lts-alpine
WORKDIR /app

COPY --from=builder /workspace/dist/apps/publisher .

ENV PORT=3334
EXPOSE 3334
RUN npm install --production
RUN npm install reflect-metadata tslib rxjs @nestjs/platform-express

CMD node ./main.js


