FROM node:lts-alpine
WORKDIR /app

COPY --from=builder /workspace/dist/apps/publisher .

ENV PORT=3334
EXPOSE 3334
RUN npm install --production
RUN npm install reflect-metadata tslib rxjs @nestjs/platform-express

CMD node ./main.js


