FROM node:lts-alpine
WORKDIR /app

RUN addgroup -g 1001 -S iverify && adduser -u 1001 -S iverify  -G iverify 
RUN chown -R iverify:iverify /app

USER iverify

COPY ./dist/apps/api .

ENV PORT=3333
EXPOSE 3333
RUN npm install --production
RUN npm install reflect-metadata tslib rxjs @nestjs/platform-express mysql

CMD node ./main.js


